export const customFonts = {
  'Axiforma-Black': require('../assets/Fonts/Axiforma-Black.ttf'),
  'Axiforma-BlackItalic': require('../assets/Fonts/Axiforma-BlackItalic.ttf'),
  'Axiforma-Bold': require('../assets/Fonts/Axiforma-Bold.ttf'),
  'Axiforma-BoldItalic': require('../assets/Fonts/Axiforma-BoldItalic.ttf'),
  'Axiforma-Book': require('../assets/Fonts/Axiforma-Book.ttf'),
  'Axiforma-BokItalic': require('../assets/Fonts/Axiforma-BookItalic.ttf'),
  'Axiforma-ExtraBold': require('../assets/Fonts/Axiforma-ExtraBold.ttf'),
  'Axiforma-ExtraBoldItalic': require('../assets/Fonts/Axiforma-ExtraBoldItalic.ttf'),
  'Axiforma-Heavy': require('../assets/Fonts/Axiforma-Heavy.ttf'),
  'Axiforma-HeavyItalic': require('../assets/Fonts/Axiforma-HeavyItalic.ttf'),
  'Axiforma-Italic': require('../assets/Fonts/Axiforma-Italic.ttf'),
  'Axiforma-Light': require('../assets/Fonts/Axiforma-Light.ttf'),
  'Axiforma-LightItalic': require('../assets/Fonts/Axiforma-LightItalic.ttf'),
  'Axiforma-Medium': require('../assets/Fonts/Axiforma-Medium.ttf'),
  'Axiforma-MediumItalic': require('../assets/Fonts/Axiforma-MediumItalic.ttf'),
  'Axiforma-Regular': require('../assets/Fonts/Axiforma-Regular.ttf'),
  'Axiforma-SemiBold': require('../assets/Fonts/Axiforma-SemiBold.ttf'),
  'Axiforma-SemiBoldItalic': require('../assets/Fonts/Axiforma-SemiBoldItalic.ttf'),
  'Axiforma-Thin': require('../assets/Fonts/Axiforma-Thin.ttf'),
  'Axiforma-ThinItalic': require('../assets/Fonts/Axiforma-ThinItalic.ttf'),
  'GothamPro-Black': require('../assets/Fonts/GothamPro-Black.ttf'),
  'GothamPro-BlackItlaic': require('../assets/Fonts/GothamPro-BlackItalic.ttf'),
  'GothamPro-Bold': require('../assets/Fonts/GothamPro-Bold.ttf'),
  'GothamPro-BoldItalic': require('../assets/Fonts/GothamPro-BoldItalic.ttf'),
  'GothamPro-Italic': require('../assets/Fonts/GothamPro-Italic.ttf'),
  'GothamPro-Light': require('../assets/Fonts/GothamPro-Light.ttf'),
  'GothamPro-LightItalic': require('../assets/Fonts/GothamPro-LightItalic.ttf'),
  'GothamPro-Medium': require('../assets/Fonts/GothamPro-Medium.ttf'),
  'GothamPro-MediumItalic': require('../assets/Fonts/GothamPro-MediumItalic.ttf'),
  'GothamPro': require('../assets/Fonts/GothamPro.ttf'),
  'GothamProNarrow-Bold': require('../assets/Fonts/GothamProNarrow-Bold.ttf'),
  'GothamProNarrow-Medium': require('../assets/Fonts/GothamProNarrow-Medium.ttf'),
  'Poppins-Black': require('../assets/Fonts/Poppins-Black.ttf'),
  'Poppins-BlackItalic': require('../assets/Fonts/Poppins-BlackItalic.ttf'),
  'Poppins-Bold': require('../assets/Fonts/Poppins-Bold.ttf'),
  'Poppins-BoldItalic': require('../assets/Fonts/Poppins-BoldItalic.ttf'),


  'Poppins-ExtraBold': require('../assets/Fonts/Poppins-ExtraBold.ttf'),
  'Poppins-ExtraBoldItalic': require('../assets/Fonts/Poppins-ExtraBoldItalic.ttf'),


  'Poppins-Italic': require('../assets/Fonts/Poppins-Italic.ttf'),
  'Poppins-Light': require('../assets/Fonts/Poppins-Light.ttf'),
  'Poppins-LightItalic': require('../assets/Fonts/Poppins-LightItalic.ttf'),
  'Poppins-Medium': require('../assets/Fonts/Poppins-Medium.ttf'),
  'Poppins-MediumItalic': require('../assets/Fonts/Poppins-MediumItalic.ttf'),
  'Poppins-Regular': require('../assets/Fonts/Poppins-Regular.ttf'),
  'Poppins-SemiBold': require('../assets/Fonts/Poppins-SemiBold.ttf'),
  'Poppins-SemiBoldItalic': require('../assets/Fonts/Poppins-SemiBoldItalic.ttf'),
  'Poppins-Thin': require('../assets/Fonts/Poppins-Thin.ttf'),
  'Poppins-ThinItalic': require('../assets/Fonts/Poppins-ThinItalic.ttf'),

  // Add more fonts as needed
};